temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
data <- read.table(unz(temp, "household_power_consumption.txt"),header=TRUE,sep=";")
unlink(temp)
data$Date <- as.Date(data$Date,format="%d/%m/%Y")
subData1 <- subset(data,Date=="2007-02-01")
subData2 <- subset(data,Date=="2007-02-02")
dataSubset <- rbind(subData1,subData2)
dateTime <- paste(dataSubset$Date,dataSubset$Time)
dateTime <- strptime(dateTime,"%Y-%m-%d %H:%M:%S")
activePower <- as.numeric(as.character(dataSubset$Global_active_power))
plot(dateTime,activePower,type="l",ylab="Global Active Power (kilowatts)",xlab="")