temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
data <- read.table(unz(temp, "household_power_consumption.txt"),header=TRUE,sep=";")
unlink(temp)
data$Date <- as.Date(data$Date,format="%d/%m/%Y")
subData1 <- subset(data,Date=="2007-02-01")
subData2 <- subset(data,Date=="2007-02-02")
dataSubset <- rbind(subData1,subData2)
dateTime <- paste(dataSubset$Date,dataSubset$Time)
dateTime <- strptime(dateTime,"%Y-%m-%d %H:%M:%S")
Sub_metering_1 <- as.numeric(as.character(dataSubset$Sub_metering_1))
Sub_metering_2 <- as.numeric(as.character(dataSubset$Sub_metering_2))
Sub_metering_3 <- as.numeric(as.character(dataSubset$Sub_metering_3))
plot(dateTime,Sub_metering_1,type="n",ylab="Energy sub metering",xlab="")
points(dateTime,Sub_metering_1,type="l",col="black")
points(dateTime,Sub_metering_2,type="l",col="red")
points(dateTime,Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))